---
- name: Define Drupal sites.php path
  ansible.builtin.set_fact:
    dropfactory_sites_php_path: "~{{ dropfactory_site_platform_user }}/platform/web/sites/sites.php"

#We developed the update site function later on,
#so we had to take into consideration the fact that old platforms had sites.php empty (or maybe missing)
#It's better to do the check anyway... Why am I explaining myself ?!
- name: Check Drupal sites.php file
  ansible.builtin.stat:
    path: "{{ dropfactory_sites_php_path }}"
  register: dropfactory_sites_php_stat
  become: true
  become_user: "{{ dropfactory_site_platform_user }}"

- name: Initialize Drupal sites.php if missing or empty
  ansible.builtin.copy:
    dest: "{{ dropfactory_sites_php_path }}"
    content: "<?php\n"
    mode: "0640"
    force: true
  when: not dropfactory_sites_php_stat.stat.exists or dropfactory_sites_php_stat.stat.size == 0
  become: true
  become_user: "{{ dropfactory_site_platform_user }}"

- name: Register Drupal multisite aliases for {{ dropfactory_site_main_domain }}
  ansible.builtin.blockinfile:
    path: "{{ dropfactory_sites_php_path }}"
    marker: "// {mark} DROPFACTORY SITE {{ dropfactory_site_id }} ALIASES"
    block: |
      {% for alias in dropfactory_site_aliases | default([]) %}
      $sites['{{ alias }}'] = '{{ dropfactory_site_main_domain }}';
      {% endfor %}
    state: "{{ (dropfactory_site_aliases | default([]) | length > 0) | ternary('present', 'absent') }}"
  become: true
  become_user: "{{ dropfactory_site_platform_user }}"
